"""Added message

Revision ID: 33ccec5ca9b9
Revises: 3045b3486517
Create Date: 2022-03-08 20:03:45.332391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ccec5ca9b9'
down_revision = '3045b3486517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
