"""Added message

Revision ID: c081e1eba1e0
Revises: 3045b3486517
Create Date: 2022-03-09 17:53:03.581478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c081e1eba1e0'
down_revision = '3045b3486517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
