deps:
	sudo apt install libwebkit2gtk-4.0-dev \
	build-essential \
	curl \
	wget \
	libssl-dev \
	libgtk-3-dev \
	libappindicator3-dev \
	librsvg2-dev

all:
	npm run tauri build

dev:
	npm run tauri dev